### PR TITLE
[Months] add isLessThan, isLessThanOrEqualsTo, isGreaterThan, isGreat…

### PR DESCRIPTION
**Pull request by amarocco-fa**
…erThanOrEqualsTo

### CODE REVIEW

**Comment by jodastephen** [comment]
Two things.
1) Why do you want to add these methods (rather than using `compareTo()`) ?
2) If these are to be added, all similar classes would have to be done (`Days`, `Weeks`, `Years`)

**Comment by amarocco-fa** [comment]
Hi,

I just found that m1.isLessThan(m2) is clearer than m1.compareTo(m2) < 0 and less error prone. I agree with the missing implementation requirement.

**Comment by Clockwork-Muse** [comment]
@amarocco-fa - part of the problem is that it's rare to use (and compare) months alone.  You almost always have to resolve the full calendar date.  This stems from the way that months cycle (and one has a varying number of days...) every year.  ie, "Last Month" isn't always less than the current month....

**Comment by amarocco-fa** [comment]
@Clockwork-Muse - sorry I didn't well understand what you mean.

Months, Years and co... only represents an **'amount of time'** so 3 months is always greater than 2 months. We are not dealing with Duration where 2 months (between 2015-01-01 and 2015-03-01) and (between 2015-03-01and 2015-05-01) should not be equals.

**Comment by Clockwork-Muse** [comment]
@amarocco-fa - argh, sorry, read that as `Month`.

**Comment by jodastephen** [comment]
Thanks for the effort on this. My plan is to only merge this if the JDK `Duration` class has similar methods added, so that the ThreeTen classes have a similar feel to the JDK ones. I'll leave it open, but as such I have no current plans to merge it. Sorry its not the news you wanted.

**Pull request closed without merging**
