### PR TITLE
Make Interval open for extension

### PR DESCRIPTION
**Pull request by wopeers**
Could Interval be made open for extension? Would be useful to me if I could create my own IntervalWithValue.

### CODE REVIEW

**Comment by jodastephen** [comment]
The `java.time.*` packages follow a design style for classes like these that allows them to be converted to value types in some future JVM. That requires the classes to be `final`.

**Comment by wopeers** [comment]
@raupachz The point was to allow subclassing. @jodastephen But Interval isn't in `java.time.*`

**Comment by Clockwork-Muse** [comment]
@wopeers - it might not be in `java.time.*`, but it belongs to the same conceptual space.  And in general, value types can't be subclassed, because they represent a simple collection of data, not behavior.

Do you have a link to an example?  What did you mean by "interval with value"?

**Comment by wopeers** [comment]
I'm using a library which I can pass some intervals and finds me the best fit. Here's the signature: `public <T extends Interval> T findBestFit(List<T> intervals)`. 
Now each of the intervals is associated with some data (e.g. a user) so would be nice if I could extend an Interval to hold this data so I can easily retrieve the data associated with the best fitting Interval.

**Comment by Clockwork-Muse** [comment]
Favor composition over inheritance.  And this is **really** one of those times.

Data associated _with_ an interval does not make the resulting type an "Interval".
You'd be looking for a new type that has both an interval and the relevant data.  

And that signature looks strange to me.  `<T extends Interval>` makes no sense, since `Interval` is a value type and can't be subclassed (both logically and factually).  If you're dealing with a proper composite type, the signature should look something like this: `public <T> T findBestFitByInterval(List<T> items, Function<T, Interval> interval)`.

(side note: what does "best fit" even _mean_ here?  Smallest interval? Closest to some other event?)

**Comment by MenoData** [comment]
@wopeers An example for composition can be found in my lib Time4J, see the API and implementation of [ValueInterval](http://time4j.net/javadoc-en/net/time4j/range/ValueInterval.html)

The advise of @Clockwork-Muse  is wise, favor composition over inheritance. It is originally an advise from Joshua Bloch in his book "Effective Java".

**Comment by Clockwork-Muse** [comment]
@MenoData - uh, I wouldn't consider `ValueInterval` an example of composition.  That's pretty clearly inheritance (along the lines of what @wopeers  was asking for here).  For it to be composition, you'd expect something like this:
```Java
public class Event<T> {
    Interval occurredDuring;
    T thingThatHappened;
    // No methods like isBefore(..) - get the interval and use that
}
```
... instead you're extending an interval interface, and have interval-related methods on the type.

**Comment by wopeers** [comment]
I agree with the composition over inheritance advice. It's just that that's not an option since I have no control over the library thus I can't change the signature of `public <T extends Interval> T findBestFit(List<T> intervals)`

**Comment by Clockwork-Muse** [comment]
....of course it doesn't follow the Open/Closed principle; it's a value type, it doesn't have any behavior to extend.

And the Open/Closed principle doesn't really support your use-case here.  That would be for things like performing an `abuts` with a fuzzy match or something.  Doing so would also give the class a second responsibility (the information about the other data), which is why a more relevant type would be preferred.

**Pull request closed without merging**
